# basic options
title: My-First-Blog
author: Monica
email: your-email@domain.com
description: My First log
twitter_username: 
github_username:  MonicaUnlimited

# Build settings
markdown: kramdown
theme: minima
